# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1366, 700))
        MainWindow.setMaximumSize(QtCore.QSize(1366, 700))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 49, 651, 591))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.insertButton = QtWidgets.QPushButton(self.centralwidget)
        self.insertButton.setGeometry(QtCore.QRect(735, 10, 37, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.insertButton.setFont(font)
        self.insertButton.setObjectName("insertButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 650, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(390, 10, 151, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(695, 51, 651, 591))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.moveButton = QtWidgets.QPushButton(self.centralwidget)
        self.moveButton.setGeometry(QtCore.QRect(660, 300, 36, 37))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.moveButton.setFont(font)
        self.moveButton.setText("")
        self.moveButton.setObjectName("moveButton")
        self.moveallButton = QtWidgets.QPushButton(self.centralwidget)
        self.moveallButton.setGeometry(QtCore.QRect(660, 350, 36, 37))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.moveallButton.setFont(font)
        self.moveallButton.setObjectName("moveallButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(695, 650, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton.setGeometry(QtCore.QRect(695, 10, 37, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.deleteButton.setFont(font)
        self.deleteButton.setObjectName("deleteButton")
        self.onlinelabel = QtWidgets.QLabel(self.centralwidget)
        self.onlinelabel.setGeometry(QtCore.QRect(300, 650, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.onlinelabel.setFont(font)
        self.onlinelabel.setText("")
        self.onlinelabel.setObjectName("onlinelabel")
        self.offlinelabel = QtWidgets.QLabel(self.centralwidget)
        self.offlinelabel.setGeometry(QtCore.QRect(480, 650, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.offlinelabel.setFont(font)
        self.offlinelabel.setText("")
        self.offlinelabel.setObjectName("offlinelabel")
        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchButton.setGeometry(QtCore.QRect(340, 10, 37, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.searchButton.setFont(font)
        self.searchButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchButton.setIcon(icon)
        self.searchButton.setObjectName("searchButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 321, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.testButton = QtWidgets.QPushButton(self.centralwidget)
        self.testButton.setGeometry(QtCore.QRect(550, 10, 61, 31))
        self.testButton.setObjectName("testButton")
        self.groupButton = QtWidgets.QPushButton(self.centralwidget)
        self.groupButton.setGeometry(QtCore.QRect(775, 10, 121, 31))
        self.groupButton.setObjectName("groupButton")
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(620, 10, 41, 31))
        self.clearButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("clear-aff330a8cc43c8a6510df4c77826ee96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearButton.setIcon(icon1)
        self.clearButton.setObjectName("clearButton")
        self.moveUpButton = QtWidgets.QPushButton(self.centralwidget)
        self.moveUpButton.setGeometry(QtCore.QRect(900, 10, 37, 31))
        self.moveUpButton.setText("")
        self.moveUpButton.setObjectName("moveUpButton")
        self.moveDownButton = QtWidgets.QPushButton(self.centralwidget)
        self.moveDownButton.setGeometry(QtCore.QRect(940, 10, 37, 31))
        self.moveDownButton.setText("")
        self.moveDownButton.setObjectName("moveDownButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1366, 22))
        self.menuBar.setObjectName("menuBar")
        self.menu_File = QtWidgets.QMenu(self.menuBar)
        self.menu_File.setObjectName("menu_File")
        self.menu_About = QtWidgets.QMenu(self.menuBar)
        self.menu_About.setObjectName("menu_About")
        MainWindow.setMenuBar(self.menuBar)
        self.action_Quit = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Quit.setIcon(icon2)
        self.action_Quit.setObjectName("action_Quit")
        self.action_Open = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Open.setIcon(icon3)
        self.action_Open.setObjectName("action_Open")
        self.action_About = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_About.setIcon(icon4)
        self.action_About.setObjectName("action_About")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon5)
        self.actionSave.setObjectName("actionSave")
        self.action = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../.designer/backup/split.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action.setIcon(icon6)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("check.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_2.setIcon(icon7)
        self.action_2.setObjectName("action_2")
        self.actionNew = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon8)
        self.actionNew.setObjectName("actionNew")
        self.openFromUrl = QtWidgets.QAction(MainWindow)
        self.openFromUrl.setObjectName("openFromUrl")
        self.menu_File.addAction(self.actionNew)
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addAction(self.openFromUrl)
        self.menu_File.addAction(self.actionSave)
        self.menu_File.addAction(self.action_Quit)
        self.menu_About.addAction(self.action_About)
        self.menuBar.addAction(self.menu_File.menuAction())
        self.menuBar.addAction(self.menu_About.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Another Playlist Editor"))
        self.insertButton.setText(_translate("MainWindow", "+"))
        self.label.setText(_translate("MainWindow", "Всего каналов:"))
        self.moveallButton.setText(_translate("MainWindow", ">>"))
        self.label_2.setText(_translate("MainWindow", "Всего каналов:"))
        self.deleteButton.setText(_translate("MainWindow", "-"))
        self.testButton.setText(_translate("MainWindow", "Тест"))
        self.groupButton.setText(_translate("MainWindow", "Добавить в группу"))
        self.menu_File.setTitle(_translate("MainWindow", "&Плейлист"))
        self.menu_About.setTitle(_translate("MainWindow", "&Справка"))
        self.action_Quit.setText(_translate("MainWindow", "&Выход"))
        self.action_Open.setText(_translate("MainWindow", "&Открыть"))
        self.action_About.setText(_translate("MainWindow", "&О программе"))
        self.actionSave.setText(_translate("MainWindow", "Сохранить"))
        self.action.setText(_translate("MainWindow", "Объединить листы(soon)"))
        self.action_2.setText(_translate("MainWindow", "Проверка доступности каналов"))
        self.actionNew.setText(_translate("MainWindow", "Новый"))
        self.openFromUrl.setText(_translate("MainWindow", "Открыть по ссылке"))
